### ISSUE TITLE
Questions about usage in JP/EN client

### ISSUE THREAD

**Issue by beckyeeky** [LockonS483/AutoJailMarker#1]
Regarding the priority list, what info shall I fill in with?
The character name from top (MT/ST/D1/.../H1/H2, as what popular CN guide indicated), or, eight numeric strings I get from clicking "try party list"?

If it is the character name that shall be filled here, I noticed if the length of name exceeds certain number, party of the name gets ommited in the HUD party list as well as the list in chatbox generated by the plugin. 
e.g. **"Aaaaaa Bbbbbbbbb"** will be displayed as  **"Aaaaaa Bbbbbb.."**
in this case, which kind of form above shall I fill in with?

**Comment by LockonS483** [comment]
Hey, sorry for the late reply. You should fill in the priority list with the player's names as they appear on your party list.
For example for me it would be something like "Alphinaud Levilleur"

**Comment by beckyeeky** [comment]
Thanks for the feedback, and what about the ID that exceeds certain length and gets displayed with ellipsis such as "Alphinaud Levilleur.." in the UI, shall I input with ellipsis too?

**Comment by LockonS483** [comment]
Yeah i think so. I haven't tried it but that should work.

**Comment by beckyeeky** [comment]
Ok,
Thanks again for your time!
