### ISSUE TITLE
Unable to check party prio in fight + game crash

### ISSUE THREAD

**Issue by cowbot92** [LockonS483/AutoJailMarker#14]
Plugin crashes when you press the party prio button & game will just hard crash when you get to gaols.

**Comment by annco-ff14** [comment]
same as mine too.
gotta crash game when hit goals (even not include me)
dalamud v6.2.40.0
autojail 3.0.0.0

**Comment by LockonS483** [comment]
I will look into it. Sorry! It may take some time to put a group together to go back into uwu

**Comment by Cyenia** [comment]
@cowbot92 can you post the error message from /xllog when you press the party prio button?

If the game crashes on goals, can you post the dalamud.log file from %appdata%\XIVLauncher?
You must copy the dalamud.log immediately after the crash without restarting the game, otherwise the file will be overwritten.

**Comment by LockonS483** [comment]
Hey, the problem should be fixed now. Please reinstall the plugin and see if it helps!

**Comment by Cyenia** [comment]
What did you change?

**Comment by LockonS483** [comment]
UpdateOrderedParty was the problem since the partylist logic was changed thanks to DalamudApi.PartyList

**Comment by Cyenia** [comment]
But the DalamudApi.PartyList is not in the right order. That is why I had to build it like this

**Comment by LockonS483** [comment]
Hmm interesting. The limited testing I did seemed to look like it worked but i'll have another look in a second

**Comment by Cyenia** [comment]
The DalamudApi.Partylist orders the list based on how the players spawn. [PartyList.cs](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Game/ClientState/Party/PartyList.cs/#L75)

**Comment by LockonS483** [comment]
Certainly seems like it. I'll probably redo the UI-based name capturing

**Comment by Cyenia** [comment]
Do you also get this error, if so can you send me the error? Because I can use the plugin like this

**Comment by LockonS483** [comment]
The game does not crash but the plugin does for me. It throws an index out of range.

**Comment by Cyenia** [comment]
Where does it throw an index out of range?

**Comment by LockonS483** [comment]
line 201. On mine it is:
`                    if (aPartyListMemberName[0] != aPartyMemberName[2]) continue;
`

**Comment by Cyenia** [comment]
Hmm okay. I found something interesting in FFXIVClientStructs.FFXIV.Client.Game.Group. I'll check that.

**Comment by LockonS483** [comment]
https://discord.gg/v5tZNBtT
why don't we discuss on discord. I think i found the problem
