### ISSUE TITLE
Automatically get the player names in the priority list

### ISSUE THREAD

**Issue by JasonLucas** [LockonS483/AutoJailMarker#15]
Can you make it so the plugin automatically gets the player names in the party and populate the priority list automatically?
Thank you!

**Comment by LockonS483** [comment]
Hey, QoL features are in the works. Thank you for your patience

**Comment by LockonS483** [comment]
This has been implemented. Thank you for the suggestion!

**Comment by Cyenia** [comment]
The next version will additionally have exactly this button
