### ISSUE TITLE
Crashing after XIVLuncher update

### ISSUE THREAD

**Issue by 720mmHowizter** [LockonS483/AutoJailMarker#2]
Started to crash a lot randomly at the time of this post after a XIVlauncher update, when just doing random stuff like gardening and retainers.

**Comment by LockonS483** [comment]
It's not caused crashes for me. Is this easily reproducible?

**Comment by Metadono** [comment]
It crashes 3~2s after I join a party although it doesn't if it's cross-world.

**Comment by LockonS483** [comment]
This does appear to be happening. I will look into it. Thank you!
