### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by Clocktown** [LockonS483/AutoJailMarker#9]
Currently the plugin fails to install for me (same for dynamez' Fork).

I simply get an Installer Error. The Log in my Chat says `[JailMarker] -Initializing Plugin-`.

I restarted multiple times as the error message suggested but it doesn't change anything.

Edit:

I managed to get a working build by using dynamez' Fork and updating it with your latest signature.

**Comment by LockonS483** [comment]
I uploaded a new build. Should work now according to the readme.
